language: node_js
sudo: false
node_js:
  - "node"
cache:
  yarn: true
before_install:
  # remove default yarn
  - sudo rm -rf $(dirname $(which yarn))/yarn*
  # download latest
  - rm -rf ~/.yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - echo 'export PATH="${PATH}:${HOME}/.yarn/bin"' >> $BASH_ENV
install:
  - yarn install
deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$