language: node_js
sudo: false
node_js:
  - "node"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$